name: chicago
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - numpy
    - scipy
    - matplotlib
    - pandas
    - nb_conda
    - geopandas
    - shapely
    - cartopy
    - jupyter
    - seaborn
    - descartes
    - xlrd
    - scikit-learn
